/// Clase que contiene todas las traducciones de la app
class AppStrings {
  static String get(String key, String language) {
    return _translations[language]?[key] ?? _translations['es']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    // ESPAÑOL
    'es': {
      // General
      'settings': 'Ajustes',
      'close': 'Cerrar',
      'play': 'Jugar',
      'guide': 'Guía',
      'back': 'Volver',
      'retry': 'Reintentar',
      'play_again': 'Jugar de nuevo',
      'exit_menu': 'Salir al menú',
      'restart': 'Reiniciar',
      'exit': 'Salir',
      'next_level': 'Siguiente Nivel',
      'undo': 'Deshacer',
      'or': 'o',

      // Ajustes
      'dark_theme': 'Tema oscuro',
      'activated': 'Activado',
      'deactivated': 'Desactivado',
      'music_volume': 'Volumen de música',
      'effects_volume': 'Volumen de efectos',
      'mute_all': 'Silenciar todo',
      'muted': 'Silenciado',
      'with_sound': 'Con sonido',
      'streak': 'Racha',
      'consecutive_days': 'Días jugando consecutivos',
      'days': 'días',
      'play_as_guest': 'Jugar como invitado',
      'continue_without_account': 'Continuar sin cuenta',
      'switch_account': 'Cambiar de cuenta',
      'login_other_account': 'Iniciar sesión con otra cuenta',
      'language': 'Idioma',
      'select_language': 'Seleccionar idioma',

      // Mensajes
      'now_playing_as_guest': 'Ahora estás jugando como invitado',
      'error_guest_mode': 'Error al cambiar a modo invitado',

      // Selección de modo
      'select_mode': 'Selecciona\nModalidad',
      'time_attack': 'Contrarreloj',
      'perfect': 'Perfecto',
      'speed': 'Velocidad',
      'survival_pro': 'Supervivencia\nPRO',
      'perfect_pro': 'Perfecto\nPRO',
      'hard_pro': 'Difícil\nPRO',

      // Game Over
      'congratulations': '¡Felicidades!',
      'game_over': 'Game Over',
      'completed_in': 'Has completado el Sudoku en',
      'made_error': 'Cometiste un error. ¡Inténtalo de nuevo!',
      'time_up': '¡Se acabó el tiempo!',
      'try_again': 'Inténtalo de nuevo',
      'what_to_do': '¿Qué deseas hacer?',
      'score': 'Puntuación',
      'final_score': 'Puntuación final',
      'level_completed': '¡Has completado el nivel!',
      'level_failed': 'No lograste completar el nivel a tiempo.',
      'moves': 'Movimientos',
      'moves_made': 'Movimientos realizados',
      'time_remaining': 'Tiempo restante',

      // Sudoku
      'pencil': 'Lápiz',
      'notes': 'Notas',
      'erase': 'Borrar',
      'hint': 'Pista',

      // Login
      'welcome': 'Bienvenido',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'no_account': '¿No tienes cuenta?',
      'have_account': '¿Ya tienes cuenta?',
      'username_or_email': 'Usuario o email',
      'forgot_password': '¿Has olvidado la contraseña?',
      'continue_with_google': 'Continuar con Google',
      'terms_intro': 'Al hacer clic en continuar, aceptas nuestros ',
      'terms_of_service': 'Términos de servicio',
      'and': ' y ',
      'privacy_policy': 'Política de privacidad',
      'error_login': 'Error al iniciar sesión',
      'error_guest': 'Error al crear sesión de invitado',

      // Registro
      'username': 'Usuario',
      'confirm_password': 'Confirmar contraseña',
      'create_account': 'Crear Cuenta',
      'add_your_data': 'Añade tus datos para\ncrear una cuenta',
      'email_placeholder': 'correoelectrónico@dominio.com',
      'error_register': 'Error al registrarse',

      // Pantalla principal
      'missions': 'MISIONES',
      'get_pro': 'Adquiere MINIFUN PRO por',

      // Guías
      'guide_of': 'Guía de',
      'objective': 'Objetivo',
      'instructions': 'Instrucciones',
      'controls': 'Controles',
      'understood': 'Entendido',

      // Guías Snake
      'snake_objective': 'Controla la serpiente para comer manzanas y crecer lo máximo posible sin chocar con las paredes o contigo mismo.',
      'snake_inst_1': 'La serpiente se mueve constantemente en la dirección seleccionada',
      'snake_inst_2': 'Cada manzana que comas hará crecer tu serpiente',
      'snake_inst_3': 'Tu puntuación aumenta con cada manzana consumida',
      'snake_inst_4': 'El juego termina si chocas con las paredes o con tu propio cuerpo',
      'snake_inst_5': 'Intenta conseguir la puntuación más alta posible',
      'control_up': 'Arriba',
      'control_up_desc': 'Desliza hacia arriba o presiona el botón arriba del joystick',
      'control_down': 'Abajo',
      'control_down_desc': 'Desliza hacia abajo o presiona el botón abajo del joystick',
      'control_left': 'Izquierda',
      'control_left_desc': 'Desliza hacia la izquierda o presiona el botón izquierda',
      'control_right': 'Derecha',
      'control_right_desc': 'Desliza hacia la derecha o presiona el botón derecha',
      'control_joystick': 'Joystick Virtual',
      'control_joystick_desc': 'Usa el D-Pad en la esquina inferior derecha',

      // Guías Sudoku
      'sudoku_objective': 'Completa el tablero 9x9 con números del 1 al 9, sin repetir en filas, columnas o subcuadrículas de 3x3.',
      'sudoku_inst_1': 'Cada fila debe contener los números del 1 al 9 sin repetir',
      'sudoku_inst_2': 'Cada columna debe contener los números del 1 al 9 sin repetir',
      'sudoku_inst_3': 'Cada subcuadrícula de 3x3 debe contener los números del 1 al 9 sin repetir',
      'sudoku_inst_4': 'Los números negros son fijos y no se pueden modificar',
      'sudoku_inst_5': 'Los números morados son los que tú colocas',
      'sudoku_inst_6': 'Usa el modo "Lápiz" para colocar números que serán validados',
      'sudoku_inst_7': 'Usa el modo "Notas" para escribir números candidatos sin penalización',
      'sudoku_inst_8': 'Si colocas un número incorrecto en modo lápiz, se marcará en rojo',
      'sudoku_inst_9': 'Usa el botón "Pista" si necesitas ayuda (no disponible en modo perfecto)',
      'control_select_cell': 'Seleccionar celda',
      'control_select_cell_desc': 'Toca una celda vacía para seleccionarla',
      'control_pencil': 'Lápiz',
      'control_pencil_desc': 'Coloca números definitivos que serán validados',
      'control_notes': 'Notas',
      'control_notes_desc': 'Escribe notas/candidatos sin penalización ni validación',
      'control_place_number': 'Colocar número',
      'control_place_number_desc': 'Toca un número del 1-9 para colocarlo según el modo activo',
      'control_erase': 'Borrar',
      'control_erase_desc': 'Borra el número y las notas de la celda seleccionada',
      'control_hint': 'Pista',
      'control_hint_desc': 'Revela el número correcto de una celda vacía',

      // Guías Water Sort
      'watersort_objective': 'Ordena el agua de colores en los tubos hasta que cada tubo contenga un solo color.',
      'watersort_inst_1': 'Toca un tubo para seleccionarlo',
      'watersort_inst_2': 'Toca otro tubo para verter el agua del primero al segundo',
      'watersort_inst_3': 'Solo puedes verter agua del mismo color sobre agua del mismo color',
      'watersort_inst_4': 'También puedes verter en tubos vacíos',
      'watersort_inst_5': 'Cada tubo tiene capacidad para 4 segmentos de agua',
      'watersort_inst_6': 'Completa el nivel cuando cada tubo tenga un solo color',
      'watersort_inst_7': 'Usa el botón "Deshacer" si te equivocas',
      'control_select': 'Seleccionar',
      'control_select_desc': 'Toca un tubo con agua para seleccionarlo',
      'control_pour': 'Verter',
      'control_pour_desc': 'Toca otro tubo para verter el agua seleccionada',
      'control_undo': 'Deshacer',
      'control_undo_desc': 'Deshace el último movimiento realizado',
      'control_restart': 'Reiniciar',
      'control_restart_desc': 'Reinicia el nivel desde el principio',
    },

    // ENGLISH
    'en': {
      // General
      'settings': 'Settings',
      'close': 'Close',
      'play': 'Play',
      'guide': 'Guide',
      'back': 'Back',
      'retry': 'Retry',
      'play_again': 'Play again',
      'exit_menu': 'Exit to menu',
      'restart': 'Restart',
      'exit': 'Exit',
      'next_level': 'Next Level',
      'undo': 'Undo',
      'or': 'or',

      // Settings
      'dark_theme': 'Dark theme',
      'activated': 'Enabled',
      'deactivated': 'Disabled',
      'music_volume': 'Music volume',
      'effects_volume': 'Effects volume',
      'mute_all': 'Mute all',
      'muted': 'Muted',
      'with_sound': 'Sound on',
      'streak': 'Streak',
      'consecutive_days': 'Consecutive days playing',
      'days': 'days',
      'play_as_guest': 'Play as guest',
      'continue_without_account': 'Continue without account',
      'switch_account': 'Switch account',
      'login_other_account': 'Login with another account',
      'language': 'Language',
      'select_language': 'Select language',

      // Messages
      'now_playing_as_guest': 'Now playing as guest',
      'error_guest_mode': 'Error switching to guest mode',

      // Mode selection
      'select_mode': 'Select\nMode',
      'time_attack': 'Time Attack',
      'perfect': 'Perfect',
      'speed': 'Speed',
      'survival_pro': 'Survival\nPRO',
      'perfect_pro': 'Perfect\nPRO',
      'hard_pro': 'Hard\nPRO',

      // Game Over
      'congratulations': 'Congratulations!',
      'game_over': 'Game Over',
      'completed_in': 'You completed the Sudoku in',
      'made_error': 'You made an error. Try again!',
      'time_up': 'Time is up!',
      'try_again': 'Try again',
      'what_to_do': 'What would you like to do?',
      'score': 'Score',
      'final_score': 'Final score',
      'level_completed': 'You completed the level!',
      'level_failed': 'You failed to complete the level in time.',
      'moves': 'Moves',
      'moves_made': 'Moves made',
      'time_remaining': 'Time remaining',

      // Sudoku
      'pencil': 'Pencil',
      'notes': 'Notes',
      'erase': 'Erase',
      'hint': 'Hint',

      // Login
      'welcome': 'Welcome',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'register': 'Register',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'username_or_email': 'Username or email',
      'forgot_password': 'Forgot your password?',
      'continue_with_google': 'Continue with Google',
      'terms_intro': 'By clicking continue, you accept our ',
      'terms_of_service': 'Terms of Service',
      'and': ' and ',
      'privacy_policy': 'Privacy Policy',
      'error_login': 'Error logging in',
      'error_guest': 'Error creating guest session',

      // Register
      'username': 'Username',
      'confirm_password': 'Confirm password',
      'create_account': 'Create Account',
      'add_your_data': 'Add your data to\ncreate an account',
      'email_placeholder': 'email@domain.com',
      'error_register': 'Error registering',

      // Main screen
      'missions': 'MISSIONS',
      'get_pro': 'Get MINIFUN PRO for',

      // Guides
      'guide_of': 'Guide for',
      'objective': 'Objective',
      'instructions': 'Instructions',
      'controls': 'Controls',
      'understood': 'Got it',

      // Snake Guides
      'snake_objective': 'Control the snake to eat apples and grow as long as possible without hitting the walls or yourself.',
      'snake_inst_1': 'The snake moves constantly in the selected direction',
      'snake_inst_2': 'Each apple you eat makes your snake grow',
      'snake_inst_3': 'Your score increases with each apple eaten',
      'snake_inst_4': 'The game ends if you hit the walls or your own body',
      'snake_inst_5': 'Try to get the highest score possible',
      'control_up': 'Up',
      'control_up_desc': 'Swipe up or press the up button on the joystick',
      'control_down': 'Down',
      'control_down_desc': 'Swipe down or press the down button on the joystick',
      'control_left': 'Left',
      'control_left_desc': 'Swipe left or press the left button',
      'control_right': 'Right',
      'control_right_desc': 'Swipe right or press the right button',
      'control_joystick': 'Virtual Joystick',
      'control_joystick_desc': 'Use the D-Pad in the bottom right corner',

      // Sudoku Guides
      'sudoku_objective': 'Complete the 9x9 board with numbers 1-9, without repeating in rows, columns, or 3x3 subgrids.',
      'sudoku_inst_1': 'Each row must contain numbers 1-9 without repeating',
      'sudoku_inst_2': 'Each column must contain numbers 1-9 without repeating',
      'sudoku_inst_3': 'Each 3x3 subgrid must contain numbers 1-9 without repeating',
      'sudoku_inst_4': 'Black numbers are fixed and cannot be changed',
      'sudoku_inst_5': 'Purple numbers are the ones you place',
      'sudoku_inst_6': 'Use "Pencil" mode to place numbers that will be validated',
      'sudoku_inst_7': 'Use "Notes" mode to write candidate numbers without penalty',
      'sudoku_inst_8': 'If you place an incorrect number in pencil mode, it will be marked in red',
      'sudoku_inst_9': 'Use the "Hint" button if you need help (not available in perfect mode)',
      'control_select_cell': 'Select cell',
      'control_select_cell_desc': 'Tap an empty cell to select it',
      'control_pencil': 'Pencil',
      'control_pencil_desc': 'Place definitive numbers that will be validated',
      'control_notes': 'Notes',
      'control_notes_desc': 'Write notes/candidates without penalty or validation',
      'control_place_number': 'Place number',
      'control_place_number_desc': 'Tap a number 1-9 to place it according to the active mode',
      'control_erase': 'Erase',
      'control_erase_desc': 'Erase the number and notes from the selected cell',
      'control_hint': 'Hint',
      'control_hint_desc': 'Reveals the correct number for an empty cell',

      // Water Sort Guides
      'watersort_objective': 'Sort the colored water into tubes until each tube contains only one color.',
      'watersort_inst_1': 'Tap a tube to select it',
      'watersort_inst_2': 'Tap another tube to pour water from the first to the second',
      'watersort_inst_3': 'You can only pour water of the same color onto water of the same color',
      'watersort_inst_4': 'You can also pour into empty tubes',
      'watersort_inst_5': 'Each tube can hold 4 water segments',
      'watersort_inst_6': 'Complete the level when each tube has only one color',
      'watersort_inst_7': 'Use the "Undo" button if you make a mistake',
      'control_select': 'Select',
      'control_select_desc': 'Tap a tube with water to select it',
      'control_pour': 'Pour',
      'control_pour_desc': 'Tap another tube to pour the selected water',
      'control_undo': 'Undo',
      'control_undo_desc': 'Undoes the last move made',
      'control_restart': 'Restart',
      'control_restart_desc': 'Restarts the level from the beginning',
    },

    // FRANÇAIS
    'fr': {
      // General
      'settings': 'Paramètres',
      'close': 'Fermer',
      'play': 'Jouer',
      'guide': 'Guide',
      'back': 'Retour',
      'retry': 'Réessayer',
      'play_again': 'Rejouer',
      'exit_menu': 'Quitter au menu',
      'restart': 'Redémarrer',
      'exit': 'Quitter',
      'next_level': 'Niveau Suivant',
      'undo': 'Annuler',
      'or': 'ou',

      // Settings
      'dark_theme': 'Thème sombre',
      'activated': 'Activé',
      'deactivated': 'Désactivé',
      'music_volume': 'Volume de la musique',
      'effects_volume': 'Volume des effets',
      'mute_all': 'Tout couper',
      'muted': 'Coupé',
      'with_sound': 'Avec son',
      'streak': 'Série',
      'consecutive_days': 'Jours consécutifs joués',
      'days': 'jours',
      'play_as_guest': 'Jouer en invité',
      'continue_without_account': 'Continuer sans compte',
      'switch_account': 'Changer de compte',
      'login_other_account': 'Se connecter avec un autre compte',
      'language': 'Langue',
      'select_language': 'Sélectionner la langue',

      // Messages
      'now_playing_as_guest': 'Vous jouez maintenant en invité',
      'error_guest_mode': 'Erreur lors du passage en mode invité',

      // Mode selection
      'select_mode': 'Sélectionner\nle mode',
      'time_attack': 'Contre la montre',
      'perfect': 'Parfait',
      'speed': 'Vitesse',
      'survival_pro': 'Survie\nPRO',
      'perfect_pro': 'Parfait\nPRO',
      'hard_pro': 'Difficile\nPRO',

      // Game Over
      'congratulations': 'Félicitations!',
      'game_over': 'Fin de partie',
      'completed_in': 'Vous avez terminé le Sudoku en',
      'made_error': 'Vous avez fait une erreur. Réessayez!',
      'time_up': 'Le temps est écoulé!',
      'try_again': 'Réessayez',
      'what_to_do': 'Que voulez-vous faire?',
      'score': 'Score',
      'final_score': 'Score final',
      'level_completed': 'Vous avez terminé le niveau!',
      'level_failed': 'Vous n\'avez pas réussi à terminer le niveau à temps.',
      'moves': 'Mouvements',
      'moves_made': 'Mouvements effectués',
      'time_remaining': 'Temps restant',

      // Sudoku
      'pencil': 'Crayon',
      'notes': 'Notes',
      'erase': 'Effacer',
      'hint': 'Indice',

      // Login
      'welcome': 'Bienvenue',
      'email': 'Email',
      'password': 'Mot de passe',
      'login': 'Connexion',
      'register': "S'inscrire",
      'no_account': "Pas de compte?",
      'have_account': 'Déjà un compte?',
      'username_or_email': 'Nom d\'utilisateur ou email',
      'forgot_password': 'Mot de passe oublié?',
      'continue_with_google': 'Continuer avec Google',
      'terms_intro': 'En cliquant sur continuer, vous acceptez nos ',
      'terms_of_service': 'Conditions d\'utilisation',
      'and': ' et ',
      'privacy_policy': 'Politique de confidentialité',
      'error_login': 'Erreur de connexion',
      'error_guest': 'Erreur lors de la création de la session invité',

      // Register
      'username': 'Nom d\'utilisateur',
      'confirm_password': 'Confirmer le mot de passe',
      'create_account': 'Créer un Compte',
      'add_your_data': 'Ajoutez vos données pour\ncréer un compte',
      'email_placeholder': 'email@domaine.com',
      'error_register': 'Erreur lors de l\'inscription',

      // Main screen
      'missions': 'MISSIONS',
      'get_pro': 'Obtenez MINIFUN PRO pour',

      // Guides
      'guide_of': 'Guide de',
      'objective': 'Objectif',
      'instructions': 'Instructions',
      'controls': 'Contrôles',
      'understood': 'Compris',

      // Snake Guides
      'snake_objective': 'Contrôlez le serpent pour manger des pommes et grandir le plus possible sans heurter les murs ou vous-même.',
      'snake_inst_1': 'Le serpent se déplace constamment dans la direction sélectionnée',
      'snake_inst_2': 'Chaque pomme mangée fait grandir votre serpent',
      'snake_inst_3': 'Votre score augmente avec chaque pomme mangée',
      'snake_inst_4': 'Le jeu se termine si vous heurtez les murs ou votre propre corps',
      'snake_inst_5': 'Essayez d\'obtenir le score le plus élevé possible',
      'control_up': 'Haut',
      'control_up_desc': 'Glissez vers le haut ou appuyez sur le bouton haut du joystick',
      'control_down': 'Bas',
      'control_down_desc': 'Glissez vers le bas ou appuyez sur le bouton bas du joystick',
      'control_left': 'Gauche',
      'control_left_desc': 'Glissez vers la gauche ou appuyez sur le bouton gauche',
      'control_right': 'Droite',
      'control_right_desc': 'Glissez vers la droite ou appuyez sur le bouton droite',
      'control_joystick': 'Joystick Virtuel',
      'control_joystick_desc': 'Utilisez le D-Pad dans le coin inférieur droit',

      // Sudoku Guides
      'sudoku_objective': 'Complétez la grille 9x9 avec les chiffres 1-9, sans répétition dans les lignes, colonnes ou sous-grilles 3x3.',
      'sudoku_inst_1': 'Chaque ligne doit contenir les chiffres 1-9 sans répétition',
      'sudoku_inst_2': 'Chaque colonne doit contenir les chiffres 1-9 sans répétition',
      'sudoku_inst_3': 'Chaque sous-grille 3x3 doit contenir les chiffres 1-9 sans répétition',
      'sudoku_inst_4': 'Les chiffres noirs sont fixes et ne peuvent pas être modifiés',
      'sudoku_inst_5': 'Les chiffres violets sont ceux que vous placez',
      'sudoku_inst_6': 'Utilisez le mode "Crayon" pour placer des chiffres qui seront validés',
      'sudoku_inst_7': 'Utilisez le mode "Notes" pour écrire des chiffres candidats sans pénalité',
      'sudoku_inst_8': 'Si vous placez un chiffre incorrect en mode crayon, il sera marqué en rouge',
      'sudoku_inst_9': 'Utilisez le bouton "Indice" si vous avez besoin d\'aide (non disponible en mode parfait)',
      'control_select_cell': 'Sélectionner une cellule',
      'control_select_cell_desc': 'Appuyez sur une cellule vide pour la sélectionner',
      'control_pencil': 'Crayon',
      'control_pencil_desc': 'Placez des chiffres définitifs qui seront validés',
      'control_notes': 'Notes',
      'control_notes_desc': 'Écrivez des notes/candidats sans pénalité ni validation',
      'control_place_number': 'Placer un chiffre',
      'control_place_number_desc': 'Appuyez sur un chiffre 1-9 pour le placer selon le mode actif',
      'control_erase': 'Effacer',
      'control_erase_desc': 'Efface le chiffre et les notes de la cellule sélectionnée',
      'control_hint': 'Indice',
      'control_hint_desc': 'Révèle le chiffre correct pour une cellule vide',

      // Water Sort Guides
      'watersort_objective': 'Triez l\'eau colorée dans les tubes jusqu\'à ce que chaque tube ne contienne qu\'une seule couleur.',
      'watersort_inst_1': 'Appuyez sur un tube pour le sélectionner',
      'watersort_inst_2': 'Appuyez sur un autre tube pour verser l\'eau du premier au second',
      'watersort_inst_3': 'Vous ne pouvez verser de l\'eau que sur de l\'eau de la même couleur',
      'watersort_inst_4': 'Vous pouvez également verser dans des tubes vides',
      'watersort_inst_5': 'Chaque tube peut contenir 4 segments d\'eau',
      'watersort_inst_6': 'Complétez le niveau lorsque chaque tube n\'a qu\'une seule couleur',
      'watersort_inst_7': 'Utilisez le bouton "Annuler" si vous faites une erreur',
      'control_select': 'Sélectionner',
      'control_select_desc': 'Appuyez sur un tube avec de l\'eau pour le sélectionner',
      'control_pour': 'Verser',
      'control_pour_desc': 'Appuyez sur un autre tube pour verser l\'eau sélectionnée',
      'control_undo': 'Annuler',
      'control_undo_desc': 'Annule le dernier mouvement effectué',
      'control_restart': 'Redémarrer',
      'control_restart_desc': 'Redémarre le niveau depuis le début',
    },

    // PORTUGUÊS
    'pt': {
      // General
      'settings': 'Configurações',
      'close': 'Fechar',
      'play': 'Jogar',
      'guide': 'Guia',
      'back': 'Voltar',
      'retry': 'Tentar novamente',
      'play_again': 'Jogar novamente',
      'exit_menu': 'Sair para o menu',
      'restart': 'Reiniciar',
      'exit': 'Sair',
      'next_level': 'Próximo Nível',
      'undo': 'Desfazer',
      'or': 'ou',

      // Settings
      'dark_theme': 'Tema escuro',
      'activated': 'Ativado',
      'deactivated': 'Desativado',
      'music_volume': 'Volume da música',
      'effects_volume': 'Volume dos efeitos',
      'mute_all': 'Silenciar tudo',
      'muted': 'Silenciado',
      'with_sound': 'Com som',
      'streak': 'Sequência',
      'consecutive_days': 'Dias consecutivos jogando',
      'days': 'dias',
      'play_as_guest': 'Jogar como convidado',
      'continue_without_account': 'Continuar sem conta',
      'switch_account': 'Trocar de conta',
      'login_other_account': 'Entrar com outra conta',
      'language': 'Idioma',
      'select_language': 'Selecionar idioma',

      // Messages
      'now_playing_as_guest': 'Agora você está jogando como convidado',
      'error_guest_mode': 'Erro ao mudar para modo convidado',

      // Mode selection
      'select_mode': 'Selecionar\nModo',
      'time_attack': 'Contra o tempo',
      'perfect': 'Perfeito',
      'speed': 'Velocidade',
      'survival_pro': 'Sobrevivência\nPRO',
      'perfect_pro': 'Perfeito\nPRO',
      'hard_pro': 'Difícil\nPRO',

      // Game Over
      'congratulations': 'Parabéns!',
      'game_over': 'Fim de jogo',
      'completed_in': 'Você completou o Sudoku em',
      'made_error': 'Você cometeu um erro. Tente novamente!',
      'time_up': 'O tempo acabou!',
      'try_again': 'Tente novamente',
      'what_to_do': 'O que você quer fazer?',
      'score': 'Pontuação',
      'final_score': 'Pontuação final',
      'level_completed': 'Você completou o nível!',
      'level_failed': 'Você não conseguiu completar o nível a tempo.',
      'moves': 'Movimentos',
      'moves_made': 'Movimentos realizados',
      'time_remaining': 'Tempo restante',

      // Sudoku
      'pencil': 'Lápis',
      'notes': 'Notas',
      'erase': 'Apagar',
      'hint': 'Dica',

      // Login
      'welcome': 'Bem-vindo',
      'email': 'Email',
      'password': 'Senha',
      'login': 'Entrar',
      'register': 'Registrar',
      'no_account': 'Não tem uma conta?',
      'have_account': 'Já tem uma conta?',
      'username_or_email': 'Usuário ou email',
      'forgot_password': 'Esqueceu sua senha?',
      'continue_with_google': 'Continuar com Google',
      'terms_intro': 'Ao clicar em continuar, você aceita nossos ',
      'terms_of_service': 'Termos de Serviço',
      'and': ' e ',
      'privacy_policy': 'Política de Privacidade',
      'error_login': 'Erro ao entrar',
      'error_guest': 'Erro ao criar sessão de convidado',

      // Register
      'username': 'Usuário',
      'confirm_password': 'Confirmar senha',
      'create_account': 'Criar Conta',
      'add_your_data': 'Adicione seus dados para\ncriar uma conta',
      'email_placeholder': 'email@dominio.com',
      'error_register': 'Erro ao registrar',

      // Main screen
      'missions': 'MISSÕES',
      'get_pro': 'Obtenha MINIFUN PRO por',

      // Guides
      'guide_of': 'Guia de',
      'objective': 'Objetivo',
      'instructions': 'Instruções',
      'controls': 'Controles',
      'understood': 'Entendido',

      // Snake Guides
      'snake_objective': 'Controle a cobra para comer maçãs e crescer o máximo possível sem bater nas paredes ou em você mesmo.',
      'snake_inst_1': 'A cobra se move constantemente na direção selecionada',
      'snake_inst_2': 'Cada maçã que você come faz sua cobra crescer',
      'snake_inst_3': 'Sua pontuação aumenta com cada maçã comida',
      'snake_inst_4': 'O jogo termina se você bater nas paredes ou no seu próprio corpo',
      'snake_inst_5': 'Tente conseguir a maior pontuação possível',
      'control_up': 'Cima',
      'control_up_desc': 'Deslize para cima ou pressione o botão cima do joystick',
      'control_down': 'Baixo',
      'control_down_desc': 'Deslize para baixo ou pressione o botão baixo do joystick',
      'control_left': 'Esquerda',
      'control_left_desc': 'Deslize para a esquerda ou pressione o botão esquerda',
      'control_right': 'Direita',
      'control_right_desc': 'Deslize para a direita ou pressione o botão direita',
      'control_joystick': 'Joystick Virtual',
      'control_joystick_desc': 'Use o D-Pad no canto inferior direito',

      // Sudoku Guides
      'sudoku_objective': 'Complete o tabuleiro 9x9 com números de 1-9, sem repetir em linhas, colunas ou subgrades 3x3.',
      'sudoku_inst_1': 'Cada linha deve conter os números 1-9 sem repetir',
      'sudoku_inst_2': 'Cada coluna deve conter os números 1-9 sem repetir',
      'sudoku_inst_3': 'Cada subgrade 3x3 deve conter os números 1-9 sem repetir',
      'sudoku_inst_4': 'Os números pretos são fixos e não podem ser alterados',
      'sudoku_inst_5': 'Os números roxos são os que você coloca',
      'sudoku_inst_6': 'Use o modo "Lápis" para colocar números que serão validados',
      'sudoku_inst_7': 'Use o modo "Notas" para escrever números candidatos sem penalidade',
      'sudoku_inst_8': 'Se você colocar um número incorreto no modo lápis, ele será marcado em vermelho',
      'sudoku_inst_9': 'Use o botão "Dica" se precisar de ajuda (não disponível no modo perfeito)',
      'control_select_cell': 'Selecionar célula',
      'control_select_cell_desc': 'Toque em uma célula vazia para selecioná-la',
      'control_pencil': 'Lápis',
      'control_pencil_desc': 'Coloque números definitivos que serão validados',
      'control_notes': 'Notas',
      'control_notes_desc': 'Escreva notas/candidatos sem penalidade ou validação',
      'control_place_number': 'Colocar número',
      'control_place_number_desc': 'Toque em um número 1-9 para colocá-lo de acordo com o modo ativo',
      'control_erase': 'Apagar',
      'control_erase_desc': 'Apaga o número e as notas da célula selecionada',
      'control_hint': 'Dica',
      'control_hint_desc': 'Revela o número correto para uma célula vazia',

      // Water Sort Guides
      'watersort_objective': 'Organize a água colorida nos tubos até que cada tubo contenha apenas uma cor.',
      'watersort_inst_1': 'Toque em um tubo para selecioná-lo',
      'watersort_inst_2': 'Toque em outro tubo para despejar a água do primeiro para o segundo',
      'watersort_inst_3': 'Você só pode despejar água da mesma cor sobre água da mesma cor',
      'watersort_inst_4': 'Você também pode despejar em tubos vazios',
      'watersort_inst_5': 'Cada tubo pode conter 4 segmentos de água',
      'watersort_inst_6': 'Complete o nível quando cada tubo tiver apenas uma cor',
      'watersort_inst_7': 'Use o botão "Desfazer" se cometer um erro',
      'control_select': 'Selecionar',
      'control_select_desc': 'Toque em um tubo com água para selecioná-lo',
      'control_pour': 'Despejar',
      'control_pour_desc': 'Toque em outro tubo para despejar a água selecionada',
      'control_undo': 'Desfazer',
      'control_undo_desc': 'Desfaz o último movimento realizado',
      'control_restart': 'Reiniciar',
      'control_restart_desc': 'Reinicia o nível desde o início',
    },
  };
}
