/// Clase que contiene todas las traducciones de la app
class AppStrings {
  static String get(String key, String language) {
    return _translations[language]?[key] ?? _translations['es']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    // ESPAÑOL
    'es': {
      // General
      'settings': 'Ajustes',
      'close': 'Cerrar',
      'play': 'Jugar',
      'guide': 'Guía',
      'back': 'Volver',
      'retry': 'Reintentar',
      'play_again': 'Jugar de nuevo',
      'exit_menu': 'Salir al menú',
      'restart': 'Reiniciar',
      'exit': 'Salir',
      'next_level': 'Siguiente Nivel',
      'undo': 'Deshacer',
      'or': 'o',

      // Ajustes
      'dark_theme': 'Tema oscuro',
      'activated': 'Activado',
      'deactivated': 'Desactivado',
      'music_volume': 'Volumen de música',
      'effects_volume': 'Volumen de efectos',
      'mute_all': 'Silenciar todo',
      'muted': 'Silenciado',
      'with_sound': 'Con sonido',
      'streak': 'Racha',
      'consecutive_days': 'Días jugando consecutivos',
      'days': 'días',
      'play_as_guest': 'Jugar como invitado',
      'continue_without_account': 'Continuar sin cuenta',
      'switch_account': 'Cambiar de cuenta',
      'login_other_account': 'Iniciar sesión con otra cuenta',
      'language': 'Idioma',
      'select_language': 'Seleccionar idioma',

      // Mensajes
      'now_playing_as_guest': 'Ahora estás jugando como invitado',
      'error_guest_mode': 'Error al cambiar a modo invitado',

      // Selección de modo
      'select_mode': 'Selecciona\nModalidad',
      'time_attack': 'Contrarreloj',
      'perfect': 'Perfecto',
      'speed': 'Velocidad',
      'survival_pro': 'Supervivencia\nPRO',
      'perfect_pro': 'Perfecto\nPRO',
      'hard_pro': 'Difícil\nPRO',

      // Game Over
      'congratulations': '¡Felicidades!',
      'game_over': 'Game Over',
      'completed_in': 'Has completado el Sudoku en',
      'made_error': 'Cometiste un error. ¡Inténtalo de nuevo!',
      'time_up': '¡Se acabó el tiempo!',
      'try_again': 'Inténtalo de nuevo',
      'what_to_do': '¿Qué deseas hacer?',
      'score': 'Puntuación',
      'final_score': 'Puntuación final',
      'level_completed': '¡Has completado el nivel!',
      'level_failed': 'No lograste completar el nivel a tiempo.',
      'moves': 'Movimientos',
      'moves_made': 'Movimientos realizados',
      'time_remaining': 'Tiempo restante',

      // Sudoku
      'pencil': 'Lápiz',
      'notes': 'Notas',
      'erase': 'Borrar',
      'hint': 'Pista',

      // Login
      'welcome': 'Bienvenido',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'no_account': '¿No tienes cuenta?',
      'have_account': '¿Ya tienes cuenta?',
      'username_or_email': 'Usuario o email',
      'forgot_password': '¿Has olvidado la contraseña?',
      'continue_with_google': 'Continuar con Google',
      'terms_intro': 'Al hacer clic en continuar, aceptas nuestros ',
      'terms_of_service': 'Términos de servicio',
      'and': ' y ',
      'privacy_policy': 'Política de privacidad',
      'error_login': 'Error al iniciar sesión',
      'error_guest': 'Error al crear sesión de invitado',

      // Registro
      'username': 'Usuario',
      'confirm_password': 'Confirmar contraseña',
      'create_account': 'Crear Cuenta',
      'add_your_data': 'Añade tus datos para\ncrear una cuenta',
      'email_placeholder': 'correoelectrónico@dominio.com',
      'error_register': 'Error al registrarse',

      // Pantalla principal
      'missions': 'MISIONES',
      'get_pro': 'Adquiere MINIFUN PRO por',

      // Guías
      'guide_of': 'Guía de',
      'objective': 'Objetivo',
      'instructions': 'Instrucciones',
      'controls': 'Controles',
      'understood': 'Entendido',

      // Guías Snake
      'snake_objective': 'Controla la serpiente para comer manzanas y crecer lo máximo posible sin chocar con las paredes o contigo mismo.',
      'snake_inst_1': 'La serpiente se mueve constantemente en la dirección seleccionada',
      'snake_inst_2': 'Cada manzana que comas hará crecer tu serpiente',
      'snake_inst_3': 'Tu puntuación aumenta con cada manzana consumida',
      'snake_inst_4': 'El juego termina si chocas con las paredes o con tu propio cuerpo',
      'snake_inst_5': 'Intenta conseguir la puntuación más alta posible',
      'control_up': 'Arriba',
      'control_up_desc': 'Desliza hacia arriba o presiona el botón arriba',
      'control_down': 'Abajo',
      'control_down_desc': 'Desliza hacia abajo o presiona el botón abajo',
      'control_left': 'Izquierda',
      'control_left_desc': 'Desliza hacia la izquierda o presiona el botón izquierda',
      'control_right': 'Derecha',
      'control_right_desc': 'Desliza hacia la derecha o presiona el botón derecha',

      // Guías Sudoku
      'sudoku_objective': 'Completar la cuadrícula con números del 1 al 9, asegurándote de que no se repitan en:'
      'Ninguna fila horizontal'
      'Ninguna columna vertical'
      'Ningún cuadrante',           
      'sudoku_inst_1': 'Toca una casilla vacía para seleccionarla',
      'sudoku_inst_2': 'Elige un número (1-9) en el teclado inferior para rellenar la casilla',
      'sudoku_inst_3': 'Cada fila y columna debe contener los números del 1 al 9 sin repetir',
      'sudoku_inst_4': 'Los números negros son fijos y no se pueden modificar',
      'sudoku_inst_5': 'Los números morados son los que tú colocas',
      'sudoku_inst_6': 'Si colocas un número incorrecto en modo lápiz, se marcará en rojo',
      'control_pencil': 'Lápiz',
      'control_pencil_desc': 'Coloca números que serán validados',
      'control_notes': 'Notas',
      'control_notes_desc': 'Escribe los numeros que creas correctos',
      'control_erase': 'Borrar',
      'control_erase_desc': 'Usa el botón de borrar para corregir errores',
      'control_hint': 'Pista',
      'control_hint_desc': 'Revela el número correcto de una celda vacía (no disponible en modo perfecto)',

      // Guías Water Sort
      'watersort_objective': 'Organizar los líquidos de colores en tubos separados hasta que cada tubo contenga únicamente un solo color.',
      'watersort_inst_1': 'Toca un tubo para seleccionar el líquido que quieres mover',
      'watersort_inst_2': 'Toca otro tubo para verter el líquido seleccionado',
      'watersort_inst_3': 'Solo puedes verter líquido sobre el mismo color o en un tubo vacío',
      'watersort_inst_4': 'El juego termina cuando todos los líquidos están organizados por color en tubos separados',
      'control_undo': 'Deshacer',
      'control_undo_desc': 'Deshace el último movimiento realizado',
      'control_restart': 'Reiniciar',
      'control_restart_desc': 'Reinicia el nivel desde el principio',

      // Pausa
      'paused': 'PAUSA',
      'game_paused': 'Juego en Pausa',
      'resume': 'Continuar',
    },

    // ENGLISH
    'en': {
      // General
      'settings': 'Settings',
      'close': 'Close',
      'play': 'Play',
      'guide': 'Guide',
      'back': 'Back',
      'retry': 'Retry',
      'play_again': 'Play again',
      'exit_menu': 'Exit to menu',
      'restart': 'Restart',
      'exit': 'Exit',
      'next_level': 'Next Level',
      'undo': 'Undo',
      'or': 'or',

      // Settings
      'dark_theme': 'Dark theme',
      'activated': 'Enabled',
      'deactivated': 'Disabled',
      'music_volume': 'Music volume',
      'effects_volume': 'Effects volume',
      'mute_all': 'Mute all',
      'muted': 'Muted',
      'with_sound': 'Sound on',
      'streak': 'Streak',
      'consecutive_days': 'Consecutive days playing',
      'days': 'days',
      'play_as_guest': 'Play as guest',
      'continue_without_account': 'Continue without account',
      'switch_account': 'Switch account',
      'login_other_account': 'Login with another account',
      'language': 'Language',
      'select_language': 'Select language',

      // Messages
      'now_playing_as_guest': 'Now playing as guest',
      'error_guest_mode': 'Error switching to guest mode',

      // Mode selection
      'select_mode': 'Select\nMode',
      'time_attack': 'Time Attack',
      'perfect': 'Perfect',
      'speed': 'Speed',
      'survival_pro': 'Survival\nPRO',
      'perfect_pro': 'Perfect\nPRO',
      'hard_pro': 'Hard\nPRO',

      // Game Over
      'congratulations': 'Congratulations!',
      'game_over': 'Game Over',
      'completed_in': 'You completed the Sudoku in',
      'made_error': 'You made an error. Try again!',
      'time_up': 'Time is up!',
      'try_again': 'Try again',
      'what_to_do': 'What would you like to do?',
      'score': 'Score',
      'final_score': 'Final score',
      'level_completed': 'You completed the level!',
      'level_failed': 'You failed to complete the level in time.',
      'moves': 'Moves',
      'moves_made': 'Moves made',
      'time_remaining': 'Time remaining',

      // Sudoku
      'pencil': 'Pencil',
      'notes': 'Notes',
      'erase': 'Erase',
      'hint': 'Hint',

      // Login
      'welcome': 'Welcome',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'register': 'Register',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'username_or_email': 'Username or email',
      'forgot_password': 'Forgot your password?',
      'continue_with_google': 'Continue with Google',
      'terms_intro': 'By clicking continue, you accept our ',
      'terms_of_service': 'Terms of Service',
      'and': ' and ',
      'privacy_policy': 'Privacy Policy',
      'error_login': 'Error logging in',
      'error_guest': 'Error creating guest session',

      // Register
      'username': 'Username',
      'confirm_password': 'Confirm password',
      'create_account': 'Create Account',
      'add_your_data': 'Add your data to\ncreate an account',
      'email_placeholder': 'email@domain.com',
      'error_register': 'Error registering',

      // Main screen
      'missions': 'MISSIONS',
      'get_pro': 'Get MINIFUN PRO for',

      // Guides
      'guide_of': 'Guide for',
      'objective': 'Objective',
      'instructions': 'Instructions',
      'controls': 'Controls',
      'understood': 'Got it',

      // Snake Guides
      'snake_objective': 'Control the snake to eat apples and grow as long as possible without hitting the walls or yourself.',
      'snake_inst_1': 'The snake moves constantly in the selected direction',
      'snake_inst_2': 'Each apple you eat makes your snake grow',
      'snake_inst_3': 'Your score increases with each apple eaten',
      'snake_inst_4': 'The game ends if you hit the walls or your own body',
      'snake_inst_5': 'Try to get the highest score possible',
      'control_up': 'Up',
      'control_up_desc': 'Swipe up or press the up button on the joystick',
      'control_down': 'Down',
      'control_down_desc': 'Swipe down or press the down button on the joystick',
      'control_left': 'Left',
      'control_left_desc': 'Swipe left or press the left button',
      'control_right': 'Right',
      'control_right_desc': 'Swipe right or press the right button',
      'control_joystick': 'Virtual Joystick',
      'control_joystick_desc': 'Use the D-Pad in the bottom right corner',

      // Sudoku Guides
      'sudoku_objective': 'Complete the 9x9 board with numbers 1-9, without repeating in rows, columns, or 3x3 subgrids.',
      'sudoku_inst_1': 'Each row must contain numbers 1-9 without repeating',
      'sudoku_inst_2': 'Each column must contain numbers 1-9 without repeating',
      'sudoku_inst_3': 'Each 3x3 subgrid must contain numbers 1-9 without repeating',
      'sudoku_inst_4': 'Black numbers are fixed and cannot be changed',
      'sudoku_inst_5': 'Purple numbers are the ones you place',
      'sudoku_inst_6': 'Use "Pencil" mode to place numbers that will be validated',
      'sudoku_inst_7': 'Use "Notes" mode to write candidate numbers without penalty',
      'sudoku_inst_8': 'If you place an incorrect number in pencil mode, it will be marked in red',
      'sudoku_inst_9': 'Use the "Hint" button if you need help (not available in perfect mode)',
      'control_select_cell': 'Select cell',
      'control_select_cell_desc': 'Tap an empty cell to select it',
      'control_pencil': 'Pencil',
      'control_pencil_desc': 'Place definitive numbers that will be validated',
      'control_notes': 'Notes',
      'control_notes_desc': 'Write notes/candidates without penalty or validation',
      'control_place_number': 'Place number',
      'control_place_number_desc': 'Tap a number 1-9 to place it according to the active mode',
      'control_erase': 'Erase',
      'control_erase_desc': 'Erase the number and notes from the selected cell',
      'control_hint': 'Hint',
      'control_hint_desc': 'Reveals the correct number for an empty cell',

      // Water Sort Guides
      'watersort_objective': 'Sort the colored water into tubes until each tube contains only one color.',
      'watersort_inst_1': 'Tap a tube to select it',
      'watersort_inst_2': 'Tap another tube to pour water from the first to the second',
      'watersort_inst_3': 'You can only pour water of the same color onto water of the same color',
      'watersort_inst_4': 'You can also pour into empty tubes',
      'watersort_inst_5': 'Each tube can hold 4 water segments',
      'watersort_inst_6': 'Complete the level when each tube has only one color',
      'watersort_inst_7': 'Use the "Undo" button if you make a mistake',
      'control_select': 'Select',
      'control_select_desc': 'Tap a tube with water to select it',
      'control_pour': 'Pour',
      'control_pour_desc': 'Tap another tube to pour the selected water',
      'control_undo': 'Undo',
      'control_undo_desc': 'Undoes the last move made',
      'control_restart': 'Restart',
      'control_restart_desc': 'Restarts the level from the beginning',

      // Pause
      'paused': 'PAUSED',
      'game_paused': 'Game Paused',
      'resume': 'Resume',
    },

    // CATALÀ
    'ca': {
      // General
      'settings': 'Ajustos',
      'close': 'Tancar',
      'play': 'Jugar',
      'guide': 'Guia',
      'back': 'Tornar',
      'retry': 'Reintentar',
      'play_again': 'Jugar de nou',
      'exit_menu': 'Eixir al menú',
      'restart': 'Reiniciar',
      'exit': 'Eixir',
      'next_level': 'Següent Nivell',
      'undo': 'Desfer',
      'or': 'o',

      // Ajustos
      'dark_theme': 'Tema fosc',
      'activated': 'Activat',
      'deactivated': 'Desactivat',
      'music_volume': 'Volum de música',
      'effects_volume': 'Volum d\'efectes',
      'mute_all': 'Silenciar tot',
      'muted': 'Silenciat',
      'with_sound': 'Amb so',
      'streak': 'Ratxa',
      'consecutive_days': 'Dies jugant consecutius',
      'days': 'dies',
      'play_as_guest': 'Jugar com a convidat',
      'continue_without_account': 'Continuar sense compte',
      'switch_account': 'Canviar de compte',
      'login_other_account': 'Iniciar sessió amb un altre compte',
      'language': 'Idioma',
      'select_language': 'Seleccionar idioma',

      // Missatges
      'now_playing_as_guest': 'Ara estàs jugant com a convidat',
      'error_guest_mode': 'Error al canviar a mode convidat',

      // Selecció de mode
      'select_mode': 'Selecciona\nModalitat',
      'time_attack': 'Contrarellotge',
      'perfect': 'Perfecte',
      'speed': 'Velocitat',
      'survival_pro': 'Supervivència\nPRO',
      'perfect_pro': 'Perfecte\nPRO',
      'hard_pro': 'Difícil\nPRO',

      // Game Over
      'congratulations': 'Felicitats!',
      'game_over': 'Game Over',
      'completed_in': 'Has completat el Sudoku en',
      'made_error': 'Has comés un error. Intenta-ho de nou!',
      'time_up': 'S\'ha acabat el temps!',
      'try_again': 'Intenta-ho de nou',
      'what_to_do': 'Què vols fer?',
      'score': 'Puntuació',
      'final_score': 'Puntuació final',
      'level_completed': 'Has completat el nivell!',
      'level_failed': 'No has pogut completar el nivell a temps.',
      'moves': 'Moviments',
      'moves_made': 'Moviments realitzats',
      'time_remaining': 'Temps restant',

      // Sudoku
      'pencil': 'Llapis',
      'notes': 'Notes',
      'erase': 'Esborrar',
      'hint': 'Pista',

      // Login
      'welcome': 'Benvingut',
      'email': 'Correu electrònic',
      'password': 'Contrasenya',
      'login': 'Iniciar sessió',
      'register': 'Registrar-se',
      'no_account': 'No tens compte?',
      'have_account': 'Ja tens compte?',
      'username_or_email': 'Usuari o email',
      'forgot_password': 'Has oblidat la contrasenya?',
      'continue_with_google': 'Continuar amb Google',
      'terms_intro': 'En fer clic en continuar, acceptes els nostres ',
      'terms_of_service': 'Termes de servei',
      'and': ' i ',
      'privacy_policy': 'Política de privacitat',
      'error_login': 'Error al iniciar sessió',
      'error_guest': 'Error al crear sessió de convidat',

      // Registre
      'username': 'Usuari',
      'confirm_password': 'Confirmar contrasenya',
      'create_account': 'Crear Compte',
      'add_your_data': 'Afig les teues dades per a\ncrear un compte',
      'email_placeholder': 'correuelectronic@domini.com',
      'error_register': 'Error al registrar-se',

      // Pantalla principal
      'missions': 'MISSIONS',
      'get_pro': 'Adquirix MINIFUN PRO per',

      // Guies
      'guide_of': 'Guia de',
      'objective': 'Objectiu',
      'instructions': 'Instruccions',
      'controls': 'Controls',
      'understood': 'Entés',

      // Guies Snake
      'snake_objective': 'Controla la serp per a menjar pomes i créixer el màxim possible sense xocar amb les parets o amb tu mateix.',
      'snake_inst_1': 'La serp es mou constantment en la direcció seleccionada',
      'snake_inst_2': 'Cada poma que menges farà créixer la teua serp',
      'snake_inst_3': 'La teua puntuació augmenta amb cada poma consumida',
      'snake_inst_4': 'El joc acaba si xoques amb les parets o amb el teu propi cos',
      'snake_inst_5': 'Intenta aconseguir la puntuació més alta possible',
      'control_up': 'Amunt',
      'control_up_desc': 'Llisca cap amunt o pressiona el botó amunt del joystick',
      'control_down': 'Avall',
      'control_down_desc': 'Llisca cap avall o pressiona el botó avall del joystick',
      'control_left': 'Esquerra',
      'control_left_desc': 'Llisca cap a l\'esquerra o pressiona el botó esquerra',
      'control_right': 'Dreta',
      'control_right_desc': 'Llisca cap a la dreta o pressiona el botó dreta',
      'control_joystick': 'Joystick Virtual',
      'control_joystick_desc': 'Usa el D-Pad en la cantonada inferior dreta',

      // Guies Sudoku
      'sudoku_objective': 'Completa el tauler 9x9 amb números de l\'1 al 9, sense repetir en files, columnes o subcuadrícules de 3x3.',
      'sudoku_inst_1': 'Cada fila ha de contindre els números de l\'1 al 9 sense repetir',
      'sudoku_inst_2': 'Cada columna ha de contindre els números de l\'1 al 9 sense repetir',
      'sudoku_inst_3': 'Cada subcuadrícula de 3x3 ha de contindre els números de l\'1 al 9 sense repetir',
      'sudoku_inst_4': 'Els números negres són fixos i no es poden modificar',
      'sudoku_inst_5': 'Els números morats són els que tu col·loques',
      'sudoku_inst_6': 'Usa el mode "Llapis" per a col·locar números que seran validats',
      'sudoku_inst_7': 'Usa el mode "Notes" per a escriure números candidats sense penalització',
      'sudoku_inst_8': 'Si col·loques un número incorrecte en mode llapis, es marcarà en roig',
      'sudoku_inst_9': 'Usa el botó "Pista" si necessites ajuda (no disponible en mode perfecte)',
      'control_select_cell': 'Seleccionar cel·la',
      'control_select_cell_desc': 'Toca una cel·la buida per a seleccionar-la',
      'control_pencil': 'Llapis',
      'control_pencil_desc': 'Col·loca números definitius que seran validats',
      'control_notes': 'Notes',
      'control_notes_desc': 'Escriu notes/candidats sense penalització ni validació',
      'control_place_number': 'Col·locar número',
      'control_place_number_desc': 'Toca un número de l\'1-9 per a col·locar-lo segons el mode actiu',
      'control_erase': 'Esborrar',
      'control_erase_desc': 'Esborra el número i les notes de la cel·la seleccionada',
      'control_hint': 'Pista',
      'control_hint_desc': 'Revela el número correcte d\'una cel·la buida',

      // Guies Water Sort
      'watersort_objective': 'Ordena l\'aigua de colors en els tubs fins que cada tub continga un sol color.',
      'watersort_inst_1': 'Toca un tub per a seleccionar-lo',
      'watersort_inst_2': 'Toca un altre tub per a abocar l\'aigua del primer al segon',
      'watersort_inst_3': 'Només pots abocar aigua del mateix color sobre aigua del mateix color',
      'watersort_inst_4': 'També pots abocar en tubs buits',
      'watersort_inst_5': 'Cada tub té capacitat per a 4 segments d\'aigua',
      'watersort_inst_6': 'Completa el nivell quan cada tub tinga un sol color',
      'watersort_inst_7': 'Usa el botó "Desfer" si t\'equivoques',
      'control_select': 'Seleccionar',
      'control_select_desc': 'Toca un tub amb aigua per a seleccionar-lo',
      'control_pour': 'Abocar',
      'control_pour_desc': 'Toca un altre tub per a abocar l\'aigua seleccionada',
      'control_undo': 'Desfer',
      'control_undo_desc': 'Desfà l\'últim moviment realitzat',
      'control_restart': 'Reiniciar',
      'control_restart_desc': 'Reinicia el nivell des del principi',

      // Pausa
      'paused': 'PAUSA',
      'game_paused': 'Joc en Pausa',
      'resume': 'Continuar',
    },
  };
}
