const Map<String, String> stringsEn = {
  // General
  'settings': 'Settings',
  'close': 'Close',
  'cancel': 'Cancel',
  'play': 'Play',
  'guide': 'Guide',
  'back': 'Back',
  'retry': 'Retry',
  'play_again': 'Play again',
  'exit_menu': 'Exit to menu',
  'restart': 'Restart',
  'exit': 'Exit',
  'next_level': 'Next Level',
  'undo': 'Undo',
  'or': 'or',
  'select_difficulty': 'Select Difficulty',
  'easy': 'Easy',
  'medium': 'Medium',
  'hard': 'Hard',

  // Settings
  'dark_theme': 'Dark theme',
  'activated': 'Enabled',
  'deactivated': 'Disabled',
  'music_volume': 'Music volume',
  'effects_volume': 'Effects volume',
  'mute_all': 'Mute all',
  'muted': 'Muted',
  'with_sound': 'Sound on',
  'streak': 'Streak',
  'consecutive_days': 'Consecutive days playing',
  'days': 'days',
  'guest_name': 'Guest',
  'play_as_guest': 'Play as guest',
  'continue_without_account': 'Continue without account',
  'switch_account': 'Switch account',
  'login_other_account': 'Login with another account',
  'language': 'Language',
  'select_language': 'Select language',

  // Messages
  'now_playing_as_guest': 'Now playing as guest',
  'error_guest_mode': 'Error switching to guest mode',

  // Mode selection
  'select_mode': 'Select\nMode',
  'time_attack': 'Time Attack',
  'perfect': 'Perfect',
  'speed': 'Speed',
  'survival_pro': 'Survival\nPRO',
  'perfect_pro': 'Perfect\nPRO',
  'hard_pro': 'Hard\nPRO',

  // Game Over
  'congratulations': 'Congratulations!',
  'game_over': 'Game Over',
  'completed_in': 'You completed the Sudoku in',
  'made_error': 'You made an error. Try again!',
  'time_up': 'Time is up!',
  'try_again': 'Try again',
  'what_to_do': 'What would you like to do?',
  'score': 'Score',
  'final_score': 'Final score',
  'level_label': 'Level',
  'level_completed': 'You completed the level!',
  'level_failed': 'You failed to complete the level in time.',
  'moves': 'Moves',
  'moves_made': 'Moves made',
  'time_remaining': 'Time remaining',
  'words_found': 'Words found',
  'the_word_was': 'The word was',
  'words_completed': 'Words completed',

  // Minesweeper
  'touched_mine': 'You hit a mine!',
  'victory': 'Victory!',
  'found_all_mines': 'You found all mines!',
  'time_attack_completed': 'Time attack completed!',
  'difficulty_size': 'Difficulty',
  'time_label': 'Time',

  // Sudoku
  'pencil': 'Pencil',
  'notes': 'Notes',
  'erase': 'Erase',
  'hint': 'Hint',

  // Login
  'welcome': 'Welcome',
  'email': 'Email',
  'password': 'Password',
  'login': 'Login',
  'register': 'Register',
  'no_account': "Don't have an account?",
  'have_account': 'Already have an account?',
  'username_or_email': 'Username or email',
  'forgot_password': 'Forgot your password?',
  'continue_with_google': 'Continue with Google',
  'terms_intro': 'By clicking continue, you accept our ',
  'terms_of_service': 'Terms of Service',
  'and': ' and ',
  'privacy_policy': 'Privacy Policy',
  'error_login': 'Error logging in',
  'error_guest': 'Error creating guest session',

  // Register
  'username': 'Username',
  'confirm_password': 'Confirm password',
  'create_account': 'Create Account',
  'add_your_data': 'Add your data to\ncreate an account',
  'email_placeholder': 'email@domain.com',
  'error_register': 'Error registering',

  // Password recovery
  'recover_password': 'Recover password',
  'recover_password_subtitle': 'Enter your email and we will send you a link to reset your password',
  'send_link': 'Send link',
  'email_sent': 'If the email exists, you will receive a recovery link',
  'back_to_login': 'Back to login',

  // Main screen
  'missions': 'MISSIONS',
  'daily_missions': 'Daily Missions',
  'missions_completed': 'Missions completed',
  'streak_days': 'Day streak',
  'mission_snake_play': 'Play 3 Snake games',
  'mission_snake_score': 'Reach 50 points in Snake',
  'mission_snake_score_high': 'Reach 100 points in Snake',
  'mission_watersort_levels': 'Complete 2 Water Sort levels',
  'mission_watersort_levels_more': 'Complete 5 Water Sort levels',
  'mission_sudoku_complete': 'Complete 1 Sudoku',
  'mission_sudoku_complete_more': 'Complete 3 Sudokus',
  'mission_hangman_win': 'Win 2 Hangman games',
  'mission_hangman_win_more': 'Win 5 Hangman games',
  'mission_minesweeper_win': 'Win 1 Minesweeper game',
  'mission_minesweeper_discover': 'Discover 20 cells in Minesweeper',
  'mission_wordsearch_words': 'Find 10 words in Word Search',
  'mission_wordsearch_complete': 'Complete 2 Word Searches',
  'mission_any_play': 'Play 5 games of any type',
  'mission_any_score': 'Reach 100 points in any game',
  'get_pro': 'Get MINIFUN PRO for',
  'pro_price': '€4.99',
  'pro_mode_locked': 'Get MINIFUN PRO to access this mode',
  'no_hints_left': 'You have no hints left',
  'hint_word_starts': 'The word starts here',
  'hint_safe_cell': 'This cell is safe',
  'hint_next_move': 'Suggested next move',
  'no_valid_moves': 'No valid moves available',

  // Game names
  'game_snake': 'Snake',
  'game_watersort': 'WaterSort',
  'game_word_search': 'Word Search',
  'game_hangman': 'Hangman',
  'game_minesweeper': 'Minesweeper',
  'game_sudoku': 'Sudoku',

  // Email verification
  'verify_email': 'Verify your email',
  'verify_email_desc': 'We\'ve sent you a verification email. Check your inbox (and spam folder) to activate your account.',
  'understood': 'Got it',

  // Profile
  'profile': 'Profile',
  'edit_profile': 'Edit profile',
  'change_photo': 'Change photo',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'save_changes': 'Save changes',
  'profile_updated': 'Profile updated',
  'verify_email_title': 'Verify your email',
  'verify_email_message': 'We have sent a verification email to your new address. Check your inbox (and spam folder) to verify it.',
  'delete_photo': 'Delete photo',
  'delete_photo_confirm': 'Are you sure you want to delete your profile photo?',
  'photo_deleted': 'Profile photo deleted',
  'camera_permission_denied': 'Camera permission denied. Enable it in device settings.',

  // Guides
  'guide_of': 'Guide for',
  'objective': 'Objective',
  'instructions': 'Instructions',
  'controls': 'Controls',

  // Snake Guides
  'snake_objective': 'Control the snake to eat apples and grow as long as possible without hitting the walls or yourself.',
  'snake_inst_1': 'The snake moves constantly in the selected direction',
  'snake_inst_2': 'Each apple you eat makes your snake grow',
  'snake_inst_3': 'Your score increases with each apple eaten',
  'snake_inst_4': 'The game ends if you hit the walls or your own body',
  'snake_inst_5': 'Try to get the highest score possible',
  'control_up': 'Up',
  'control_up_desc': 'Swipe up or press the up button on the joystick',
  'control_down': 'Down',
  'control_down_desc': 'Swipe down or press the down button on the joystick',
  'control_left': 'Left',
  'control_left_desc': 'Swipe left or press the left button',
  'control_right': 'Right',
  'control_right_desc': 'Swipe right or press the right button',
  'control_joystick': 'Virtual Joystick',
  'control_joystick_desc': 'Use the D-Pad in the bottom right corner',

  // Sudoku Guides
  'sudoku_objective': 'Complete the 9x9 board with numbers 1-9, without repeating in rows, columns, or 3x3 subgrids.',
  'sudoku_inst_1': 'Each row must contain numbers 1-9 without repeating',
  'sudoku_inst_2': 'Each column must contain numbers 1-9 without repeating',
  'sudoku_inst_3': 'Each 3x3 subgrid must contain numbers 1-9 without repeating',
  'sudoku_inst_4': 'Black numbers are fixed and cannot be changed',
  'sudoku_inst_5': 'Purple numbers are the ones you place',
  'sudoku_inst_6': 'Use "Pencil" mode to place numbers that will be validated',
  'sudoku_inst_7': 'Use "Notes" mode to write candidate numbers without penalty',
  'sudoku_inst_8': 'If you place an incorrect number in pencil mode, it will be marked in red',
  'sudoku_inst_9': 'Use the "Hint" button if you need help (not available in perfect mode)',
  'control_select_cell': 'Select cell',
  'control_select_cell_desc': 'Tap an empty cell to select it',
  'control_pencil': 'Pencil',
  'control_pencil_desc': 'Place definitive numbers that will be validated',
  'control_notes': 'Notes',
  'control_notes_desc': 'Write notes/candidates without penalty or validation',
  'control_place_number': 'Place number',
  'control_place_number_desc': 'Tap a number 1-9 to place it according to the active mode',
  'control_erase': 'Erase',
  'control_erase_desc': 'Erase the number and notes from the selected cell',
  'control_hint': 'Hint',
  'control_hint_desc_sudoku': 'Reveals the correct number for an empty cell',

  // Word Search
  'wordsearch_objective': 'Find all hidden words in the grid',
  'wordsearch_inst_1': 'Tap the first letter of a word',
  'wordsearch_inst_2': 'Drag your finger to the last letter of the word',
  'wordsearch_inst_3': 'Words can be horizontal, vertical, or diagonal',
  'wordsearch_inst_4': 'Words can be forward or backward',
  'wordsearch_inst_5': 'Found words will be crossed out from the list',
  'control_select_start': 'Select start',
  'control_select_start_desc': 'Tap the first letter of the word',
  'control_drag': 'Drag',
  'control_drag_desc': 'Drag to the last letter',
  'control_clear': 'Clear selection',
  'control_clear_desc': 'Clear current selection',
  'select_theme': 'Select theme',
  'theme_general': 'General',
  'theme_peliculas': 'Movies',
  'theme_musica': 'Music',
  'theme_historia': 'History',
  'bonus_word_found': 'BONUS WORD FOUND!',
  'bonus_points': '+50 points',

  // Water Sort Guides
  'watersort_objective': 'Sort the colored water into tubes until each tube contains only one color.',
  'watersort_inst_1': 'Tap a tube to select it',
  'watersort_inst_2': 'Tap another tube to pour water from the first to the second',
  'watersort_inst_3': 'You can only pour water of the same color onto water of the same color',
  'watersort_inst_4': 'You can also pour into empty tubes',
  'watersort_inst_5': 'Each tube can hold 4 water segments',
  'watersort_inst_6': 'Complete the level when each tube has only one color',
  'watersort_inst_7': 'Use the "Undo" button if you make a mistake',
  'control_select': 'Select',
  'control_select_desc': 'Tap a tube with water to select it',
  'control_pour': 'Pour',
  'control_pour_desc': 'Tap another tube to pour the selected water',
  'control_undo': 'Undo',
  'control_undo_desc': 'Undoes the last move made',
  'control_restart': 'Restart',
  'control_restart_desc': 'Restarts the level from the beginning',

  // Error and notification messages
  'max_flags_reached': 'Maximum flag limit reached!',
  'no_safe_cells_for_hint': 'No safe cells available for hint',
  'no_hints_remaining': 'You have no hints remaining',

  // Pause
  'paused': 'PAUSED',
  'game_paused': 'Game Paused',
  'resume': 'Resume',

  // Hangman
  'hangman_objective': 'Guess the hidden word letter by letter before the hangman drawing is complete.',
  'hangman_inst_1': 'You have 6 attempts to guess the word',
  'hangman_inst_2': 'Tap a letter on the keyboard to guess',
  'hangman_inst_3': 'If the letter is in the word, it will be revealed',
  'hangman_inst_4': 'If the letter is not in the word, a part of the hangman will be drawn',
  'hangman_inst_5': 'You win if you guess all letters before the drawing is complete',
  'control_guess_letter': 'Guess letter',
  'control_guess_letter_desc': 'Tap a letter on the keyboard to guess it',
  'theme_animales': 'Animals',
  'theme_paises': 'Countries',
  'theme_comida': 'Food',
  'hangman_speed': 'Speed',
  'hangman_survival': 'Survival\nPRO',

  // Minesweeper
  'minesweeper_objective': 'Reveal all squares without mines. Numbers indicate how many mines are nearby.',
  'minesweeper_inst_1': 'Tap a square to reveal it',
  'minesweeper_inst_2': 'Numbers indicate adjacent mines',
  'minesweeper_inst_3': 'Hold down a square to place a flag',
  'minesweeper_inst_4': 'If you tap a mine, you lose',
  'minesweeper_inst_5': 'You can also use the flag button to toggle flag mode',
  'control_reveal': 'Reveal',
  'control_reveal_desc': 'Tap a square to reveal its content',
  'control_flag': 'Flag',
  'control_flag_desc': 'Long press or enable flag mode to mark mines',
  'control_hint_desc_minesweeper': 'Reveals a random safe square',

  // Difficulty descriptions
  'diff_minesweeper_easy': '10x10 - 15 mines',
  'diff_minesweeper_medium': '16x16 - 40 mines',
  'diff_minesweeper_hard': '24x24 - 99 mines',
  'diff_sudoku_easy': 'Many cells filled.',
  'diff_sudoku_medium': 'Balanced challenge.',
  'diff_sudoku_hard': 'Very few hints.',
  'diff_watersort_easy': 'Entry level.',
  'diff_watersort_medium': 'More colors and tubes.',
  'diff_watersort_hard': 'Maximum complexity.',
  'diff_wordsearch_easy': '10x10 - Short words.',
  'diff_wordsearch_medium': '15x15 - Standard challenge.',
  'diff_wordsearch_hard': '20x20 - Complex words.',
  'diff_hangman_easy': '8 attempts - Common words.',
  'diff_hangman_medium': '6 attempts - Medium level.',
  'diff_hangman_hard': '4 attempts - Hard words.',
};
