const Map<String, String> stringsEs = {
  // General
  'settings': 'Ajustes',
  'close': 'Cerrar',
  'cancel': 'Cancelar',
  'play': 'Jugar',
  'guide': 'Guía',
  'back': 'Volver',
  'retry': 'Reintentar',
  'play_again': 'Jugar de nuevo',
  'exit_menu': 'Salir al menú',
  'restart': 'Reiniciar',
  'exit': 'Salir',
  'next_level': 'Siguiente Nivel',
  'undo': 'Deshacer',
  'or': 'o',
  'select_difficulty': 'Selecciona Dificultad',
  'easy': 'Fácil',
  'medium': 'Medio',
  'hard': 'Difícil',

  // Ajustes
  'dark_theme': 'Tema oscuro',
  'activated': 'Activado',
  'deactivated': 'Desactivado',
  'music_volume': 'Volumen de música',
  'effects_volume': 'Volumen de efectos',
  'mute_all': 'Silenciar todo',
  'muted': 'Silenciado',
  'with_sound': 'Con sonido',
  'streak': 'Racha',
  'consecutive_days': 'Días jugando consecutivos',
  'days': 'días',
  'guest_name': 'Invitado',
  'play_as_guest': 'Jugar como invitado',
  'continue_without_account': 'Continuar sin cuenta',
  'switch_account': 'Cambiar de cuenta',
  'login_other_account': 'Iniciar sesión con otra cuenta',
  'language': 'Idioma',
  'select_language': 'Seleccionar idioma',

  // Mensajes
  'now_playing_as_guest': 'Ahora estás jugando como invitado',
  'error_guest_mode': 'Error al cambiar a modo invitado',

  // Selección de modo
  'select_mode': 'Selecciona\nModalidad',
  'time_attack': 'Contrarreloj',
  'perfect': 'Perfecto',
  'speed': 'Velocidad',
  'survival_pro': 'Supervivencia\nPRO',
  'perfect_pro': 'Perfecto\nPRO',
  'hard_pro': 'Difícil\nPRO',

  // Game Over
  'congratulations': '¡Felicidades!',
  'game_over': 'Game Over',
  'completed_in': 'Has completado el Sudoku en',
  'made_error': 'Cometiste un error. ¡Inténtalo de nuevo!',
  'time_up': '¡Se acabó el tiempo!',
  'try_again': 'Inténtalo de nuevo',
  'what_to_do': '¿Qué deseas hacer?',
  'score': 'Puntuación',
  'final_score': 'Puntuación final',
  'level_label': 'Nivel',
  'level_completed': '¡Has completado el nivel!',
  'level_failed': 'No lograste completar el nivel a tiempo.',
  'moves': 'Movimientos',
  'moves_made': 'Movimientos realizados',
  'time_remaining': 'Tiempo restante',
  'words_found': 'Palabras encontradas',
  'the_word_was': 'La palabra era',
  'words_completed': 'Palabras completadas',

  // Buscaminas
  'touched_mine': '¡Tocaste una mina!',
  'victory': '¡Victoria!',
  'found_all_mines': '¡Encontraste todas las minas!',
  'time_attack_completed': '¡Modo Contrarreloj completado!',
  'difficulty_size': 'Dificultad',
  'time_label': 'Tiempo',

  // Sudoku
  'pencil': 'Lápiz',
  'notes': 'Notas',
  'erase': 'Borrar',
  'hint': 'Pista',

  // Login
  'welcome': 'Bienvenido',
  'email': 'Correo electrónico',
  'password': 'Contraseña',
  'login': 'Iniciar sesión',
  'register': 'Registrarse',
  'no_account': '¿No tienes cuenta?',
  'have_account': '¿Ya tienes cuenta?',
  'username_or_email': 'Usuario o email',
  'forgot_password': '¿Has olvidado la contraseña?',
  'continue_with_google': 'Continuar con Google',
  'terms_intro': 'Al hacer clic en continuar, aceptas nuestros ',
  'terms_of_service': 'Términos de servicio',
  'terms_and_conditions': 'Términos y Condiciones',
  'and': ' y ',
  'privacy_policy': 'Política de privacidad',
  'error_login': 'Error al iniciar sesión',
  'error_guest': 'Error al crear sesión de invitado',

  // Registro
  'username': 'Usuario',
  'confirm_password': 'Confirmar contraseña',
  'create_account': 'Crear Cuenta',
  'add_your_data': 'Añade tus datos para\ncrear una cuenta',
  'email_placeholder': 'correoelectrónico@dominio.com',
  'error_register': 'Error al registrarse',

  // Recuperar contraseña
  'recover_password': 'Recuperar contraseña',
  'recover_password_subtitle': 'Introduce tu email y te enviaremos un enlace para restablecer tu contraseña',
  'send_link': 'Enviar enlace',
  'email_sent': 'Si el email existe, recibirás un enlace de recuperación',
  'back_to_login': 'Volver al inicio de sesión',

  // Pantalla principal
  'missions': 'MISIONES',
  'daily_missions': 'Misiones Diarias',
  'missions_completed': 'Misiones completadas',
  'streak_days': 'Racha de días',
  'mission_snake_play': 'Juega 3 partidas de Snake',
  'mission_snake_score': 'Alcanza 50 puntos en Snake',
  'mission_snake_score_high': 'Alcanza 100 puntos en Snake',
  'mission_watersort_levels': 'Completa 2 niveles de Water Sort',
  'mission_watersort_levels_more': 'Completa 5 niveles de Water Sort',
  'mission_sudoku_complete': 'Completa 1 Sudoku',
  'mission_sudoku_complete_more': 'Completa 3 Sudokus',
  'mission_hangman_win': 'Gana 2 partidas de Ahorcado',
  'mission_hangman_win_more': 'Gana 5 partidas de Ahorcado',
  'mission_minesweeper_win': 'Gana 1 partida de Buscaminas',
  'mission_minesweeper_discover': 'Descubre 20 celdas en Buscaminas',
  'mission_wordsearch_words': 'Encuentra 10 palabras en Sopa de Letras',
  'mission_wordsearch_complete': 'Completa 2 Sopas de Letras',
  'mission_any_play': 'Juega 5 partidas de cualquier juego',
  'mission_any_score': 'Alcanza 100 puntos en cualquier juego',
  'get_pro': 'Adquiere MINIFUN PRO por',
  'pro_price': '€4.99',
  'pro_mode_locked': 'Obtén MINIFUN PRO para acceder a esta modalidad',
  'no_hints_left': 'No te quedan pistas disponibles',
  'hint_word_starts': 'La palabra empieza aquí',
  'hint_safe_cell': 'Esta celda es segura',
  'hint_next_move': 'Siguiente movimiento sugerido',
  'no_valid_moves': 'No hay movimientos válidos disponibles',

  // Nombres de juegos
  'game_snake': 'Snake',
  'game_watersort': 'WaterSort',
  'game_word_search': 'Sopa de Letras',
  'game_hangman': 'Ahorcado',
  'game_minesweeper': 'Buscaminas',
  'game_sudoku': 'Sudoku',

  // Verificación de email
  'verify_email': 'Verifica tu email',
  'verify_email_desc': 'Te hemos enviado un correo de verificación. Revisa tu bandeja de entrada (y la carpeta de spam) para activar tu cuenta.',
  'understood': 'Entendido',

  // Perfil
  'profile': 'Perfil',
  'edit_profile': 'Editar perfil',
  'change_photo': 'Cambiar foto',
  'camera': 'Cámara',
  'gallery': 'Galería',
  'save_changes': 'Guardar cambios',
  'profile_updated': 'Perfil actualizado',
  'verify_email_title': 'Verifica tu email',
  'verify_email_message': 'Te hemos enviado un correo de verificación al nuevo email. Revisa tu bandeja de entrada (y la carpeta de spam) para verificarlo.',
  'delete_photo': 'Eliminar foto',
  'delete_photo_confirm': '¿Estás seguro de que quieres eliminar tu foto de perfil?',
  'photo_deleted': 'Foto de perfil eliminada',
  'camera_permission_denied': 'Permiso de cámara denegado. Actívalo en los ajustes del dispositivo.',

  // Guías
  'guide_of': 'Guía de',
  'objective': 'Objetivo',
  'instructions': 'Instrucciones',
  'controls': 'Controles',

  // Guías Snake
  'snake_objective': 'Controla la serpiente para comer manzanas y crecer lo máximo posible sin chocar con las paredes o contigo mismo.',
  'snake_inst_1': 'La serpiente se mueve constantemente en la dirección seleccionada',
  'snake_inst_2': 'Cada manzana que comas hará crecer tu serpiente',
  'snake_inst_3': 'Tu puntuación aumenta con cada manzana consumida',
  'snake_inst_4': 'El juego termina si chocas con las paredes o con tu propio cuerpo',
  'snake_inst_5': 'Intenta conseguir la puntuación más alta posible',
  'control_up': 'Arriba',
  'control_up_desc': 'Desliza hacia arriba o presiona el botón arriba',
  'control_down': 'Abajo',
  'control_down_desc': 'Desliza hacia abajo o presiona el botón abajo',
  'control_left': 'Izquierda',
  'control_left_desc': 'Desliza hacia la izquierda o presiona el botón izquierda',
  'control_right': 'Derecha',
  'control_right_desc': 'Desliza hacia la derecha o presiona el botón derecha',
  'control_joystick': 'Joystick Virtual',
  'control_joystick_desc': 'Usa el D-Pad en la esquina inferior derecha',

  // Guías Sudoku
  'sudoku_objective': 'Completar la cuadrícula con números del 1 al 9, asegurándote de que no se repitan en:'
      'Ninguna fila horizontal'
      'Ninguna columna vertical'
      'Ningún cuadrante',
  'sudoku_inst_1': 'Toca una casilla vacía para seleccionarla',
  'sudoku_inst_2': 'Elige un número (1-9) en el teclado inferior para rellenar la casilla',
  'sudoku_inst_3': 'Cada fila y columna debe contener los números del 1 al 9 sin repetir',
  'sudoku_inst_4': 'Los números negros son fijos y no se pueden modificar',
  'sudoku_inst_5': 'Los números morados son los que tú colocas',
  'sudoku_inst_6': 'Si colocas un número incorrecto en modo lápiz, se marcará en rojo',
  'sudoku_inst_7': 'Usa el modo "Notas" para escribir números candidatos sin penalización',
  'sudoku_inst_8': 'Los errores en modo lápiz se marcan en rojo automáticamente',
  'sudoku_inst_9': 'Usa el botón "Pista" si necesitas ayuda (no disponible en modo perfecto)',
  'control_select_cell': 'Seleccionar casilla',
  'control_select_cell_desc': 'Toca una casilla vacía para seleccionarla',
  'control_pencil': 'Lápiz',
  'control_pencil_desc': 'Coloca números que serán validados',
  'control_notes': 'Notas',
  'control_notes_desc': 'Escribe los numeros que creas correctos',
  'control_place_number': 'Colocar número',
  'control_place_number_desc': 'Toca un número del 1-9 para colocarlo según el modo activo',
  'control_erase': 'Borrar',
  'control_erase_desc': 'Usa el botón de borrar para corregir errores',
  'control_hint': 'Pista',
  'control_hint_desc_sudoku': 'Revela el número correcto de una celda vacía (no disponible en modo perfecto)',

  // Sopa de Letras
  'wordsearch_objective': 'Encuentra todas las palabras ocultas en la cuadrícula',
  'wordsearch_inst_1': 'Toca la primera letra de una palabra',
  'wordsearch_inst_2': 'Arrastra el dedo hasta la última letra de la palabra',
  'wordsearch_inst_3': 'Las palabras pueden estar en horizontal, vertical o diagonal',
  'wordsearch_inst_4': 'Las palabras pueden estar al derecho o al revés',
  'wordsearch_inst_5': 'Las palabras encontradas se tacharán de la lista',
  'control_select_start': 'Seleccionar inicio',
  'control_select_start_desc': 'Toca la primera letra de la palabra',
  'control_drag': 'Arrastrar',
  'control_drag_desc': 'Arrastra hasta la última letra',
  'control_clear': 'Limpiar selección',
  'control_clear_desc': 'Limpia la selección actual',
  'select_theme': 'Seleccionar temática',
  'theme_general': 'General',
  'theme_peliculas': 'Películas',
  'theme_musica': 'Música',
  'theme_historia': 'Historia',
  'bonus_word_found': '¡PALABRA EXTRA ENCONTRADA!',
  'bonus_points': '+50 puntos',

  // Guías Water Sort
  'watersort_objective': 'Organizar los líquidos de colores en tubos separados hasta que cada tubo contenga únicamente un solo color.',
  'watersort_inst_1': 'Toca un tubo para seleccionar el líquido que quieres mover',
  'watersort_inst_2': 'Toca otro tubo para verter el líquido seleccionado',
  'watersort_inst_3': 'Solo puedes verter líquido sobre el mismo color o en un tubo vacío',
  'watersort_inst_4': 'Cada tubo puede contener hasta 4 segmentos de líquido',
  'watersort_inst_5': 'Completa el nivel cuando cada tubo tenga un solo color',
  'watersort_inst_6': 'Usa el botón "Deshacer" para corregir un movimiento',
  'watersort_inst_7': 'Los tubos vacíos son útiles para reorganizar los líquidos',
  'control_select': 'Seleccionar',
  'control_select_desc': 'Toca un tubo con líquido para seleccionarlo',
  'control_pour': 'Verter',
  'control_pour_desc': 'Toca otro tubo para verter el líquido seleccionado',
  'control_undo': 'Deshacer',
  'control_undo_desc': 'Deshace el último movimiento realizado',
  'control_restart': 'Reiniciar',
  'control_restart_desc': 'Reinicia el nivel desde el principio',

  // Mensajes de error y notificaciones
  'max_flags_reached': '¡Límite máximo de banderas alcanzado!',
  'no_safe_cells_for_hint': 'No hay casillas seguras disponibles para pista',
  'no_hints_remaining': 'No te quedan más pistas disponibles',

  // Pausa
  'paused': 'PAUSA',
  'game_paused': 'Juego en Pausa',
  'resume': 'Continuar',

  // Ahorcado
  'hangman_objective': 'Adivina la palabra oculta letra por letra antes de que se complete el dibujo del ahorcado.',
  'hangman_inst_1': 'Tienes 6 intentos para adivinar la palabra',
  'hangman_inst_2': 'Toca una letra del teclado para adivinar',
  'hangman_inst_3': 'Si la letra está en la palabra, se revelará',
  'hangman_inst_4': 'Si la letra no está, se dibujará una parte del ahorcado',
  'hangman_inst_5': 'Ganas si adivinas todas las letras antes de completar el dibujo',
  'control_guess_letter': 'Adivinar letra',
  'control_guess_letter_desc': 'Toca una letra del teclado para adivinarla',
  'theme_animales': 'Animales',
  'theme_paises': 'Países',
  'theme_comida': 'Comida',
  'hangman_speed': 'Velocidad',
  'hangman_survival': 'Supervivencia\nPRO',

  // Buscaminas
  'minesweeper_objective': 'Descubre todas las casillas sin minas. Los números indican cuántas minas hay alrededor.',
  'minesweeper_inst_1': 'Toca una casilla para revelarla',
  'minesweeper_inst_2': 'Los números indican minas adyacentes',
  'minesweeper_inst_3': 'Mantén presionada una casilla para poner una bandera',
  'minesweeper_inst_4': 'Si tocas una mina, pierdes',
  'minesweeper_inst_5': 'También puedes usar el botón de bandera para activarlas sin mantener presionado',
  'control_reveal': 'Revelar',
  'control_reveal_desc': 'Toca una casilla para revelar su contenido',
  'control_flag': 'Bandera',
  'control_flag_desc': 'Mantén pulsado o activa el modo bandera para marcar minas',
  'control_hint_desc_minesweeper': 'Revela una casilla segura aleatoria',

  // Descripciones de dificultad
  'diff_minesweeper_easy': '10x10 - 15 minas',
  'diff_minesweeper_medium': '16x16 - 40 minas',
  'diff_minesweeper_hard': '24x24 - 99 minas',
  'diff_sudoku_easy': 'Muchas celdas rellenas.',
  'diff_sudoku_medium': 'Desafío equilibrado.',
  'diff_sudoku_hard': 'Muy pocas pistas.',
  'diff_watersort_easy': 'Nivel de entrada.',
  'diff_watersort_medium': 'Más colores y tubos.',
  'diff_watersort_hard': 'Máxima complejidad.',
  'diff_wordsearch_easy': '10x10 - Palabras cortas.',
  'diff_wordsearch_medium': '15x15 - Desafío estándar.',
  'diff_wordsearch_hard': '20x20 - Palabras complejas.',
  'diff_hangman_easy': '8 intentos - Palabras comunes.',
  'diff_hangman_medium': '6 intentos - Nivel medio.',
  'diff_hangman_hard': '4 intentos - Palabras difíciles.',

  // PRO Benefits
  'pro_benefits_title': 'Beneficios de MINIFUN PRO',
  'pro_benefits_intro': 'Desbloquea los modos exclusivos:',
  'pro_benefit_snake': 'Supervivencia PRO en Snake',
  'pro_benefit_watersort': 'Difícil PRO en Water Sort',
  'pro_benefit_wordsearch': 'Perfecto PRO en Sopa de Letras',
  'pro_benefit_hangman': 'Supervivencia PRO en Ahorcado',
  'pro_benefit_minesweeper_expert': 'Experto en Buscaminas',
  'pro_benefit_minesweeper_noflags': 'Sin Banderas en Buscaminas',
  'pro_benefit_sudoku': 'Perfecto PRO en Sudoku',
};
