const Map<String, String> stringsCa = {
  // General
  'settings': 'Ajustos',
  'close': 'Tancar',
  'cancel': 'Cancel·lar',
  'play': 'Jugar',
  'guide': 'Guia',
  'back': 'Tornar',
  'retry': 'Reintentar',
  'play_again': 'Jugar de nou',
  'exit_menu': 'Eixir al menú',
  'restart': 'Reiniciar',
  'exit': 'Eixir',
  'next_level': 'Següent Nivell',
  'undo': 'Desfer',
  'or': 'o',
  'select_difficulty': 'Selecciona Dificultat',
  'select_level': 'Selecciona Nivell',
  'level': 'Nivell',
  'completed': 'Completat',
  'highest_level': 'Nivell més alt',
  'easy': 'Fàcil',
  'medium': 'Mig',
  'hard': 'Difícil',

  // Ajustos
  'dark_theme': 'Tema fosc',
  'activated': 'Activat',
  'deactivated': 'Desactivat',
  'music_volume': 'Volum de música',
  'effects_volume': 'Volum d\'efectes',
  'mute_all': 'Silenciar tot',
  'muted': 'Silenciat',
  'with_sound': 'Amb so',
  'streak': 'Ratxa',
  'consecutive_days': 'Dies jugant consecutius',
  'days': 'dies',
  'guest_name': 'Convidat',
  'play_as_guest': 'Jugar com a convidat',
  'continue_without_account': 'Continuar sense compte',
  'switch_account': 'Canviar de compte',
  'login_other_account': 'Iniciar sessió amb un altre compte',
  'language': 'Idioma',
  'select_language': 'Seleccionar idioma',

  // Missatges
  'now_playing_as_guest': 'Ara estàs jugant com a convidat',
  'error_guest_mode': 'Error al canviar a mode convidat',

  // Selecció de mode
  'select_mode': 'Selecciona\nModalitat',
  'time_attack': 'Contrarellotge',
  'perfect': 'Perfecte',
  'speed': 'Velocitat',
  'survival_pro': 'Supervivència\nPRO',
  'perfect_pro': 'Perfecte\nPRO',
  'hard_pro': 'Difícil\nPRO',

  // Game Over
  'congratulations': 'Felicitats!',
  'game_over': 'Game Over',
  'completed_in': 'Has completat el Sudoku en',
  'made_error': 'Has comés un error. Intenta-ho de nou!',
  'time_up': 'S\'ha acabat el temps!',
  'try_again': 'Intenta-ho de nou',
  'what_to_do': 'Què vols fer?',
  'score': 'Puntuació',
  'final_score': 'Puntuació final',
  'level_label': 'Nivell',
  'level_completed': 'Has completat el nivell!',
  'level_failed': 'No has pogut completar el nivell a temps.',
  'moves': 'Moviments',
  'moves_made': 'Moviments realitzats',
  'time_remaining': 'Temps restant',
  'words_found': 'Paraules trobades',
  'the_word_was': 'La paraula era',
  'words_completed': 'Paraules completades',

  // Buscamines
  'touched_mine': 'Has tocat una mina!',
  'victory': 'Victòria!',
  'found_all_mines': 'Has trobat totes les mines!',
  'time_attack_completed': 'Mode contrarellotge completat!',
  'difficulty_size': 'Dificultat',
  'time_label': 'Temps',

  // Sudoku
  'pencil': 'Llapis',
  'notes': 'Notes',
  'erase': 'Esborrar',
  'hint': 'Pista',

  // Login
  'welcome': 'Benvingut',
  'email': 'Correu electrònic',
  'password': 'Contrasenya',
  'login': 'Iniciar sessió',
  'register': 'Registrar-se',
  'no_account': 'No tens compte?',
  'have_account': 'Ja tens compte?',
  'username_or_email': 'Usuari o email',
  'forgot_password': 'Has oblidat la contrasenya?',
  'continue_with_google': 'Continuar amb Google',
  'terms_intro': 'En fer clic en continuar, acceptes els nostres ',
  'terms_of_service': 'Termes de servei',
  'and': ' i ',
  'privacy_policy': 'Política de privacitat',
  'error_login': 'Error al iniciar sessió',
  'error_guest': 'Error al crear sessió de convidat',

  // Registre
  'username': 'Usuari',
  'confirm_password': 'Confirmar contrasenya',
  'create_account': 'Crear Compte',
  'add_your_data': 'Afig les teues dades per a\ncrear un compte',
  'email_placeholder': 'correuelectronic@domini.com',
  'error_register': 'Error al registrar-se',

  // Recuperar contrasenya
  'recover_password': 'Recuperar contrasenya',
  'recover_password_subtitle': 'Introdueix el teu email i t\'enviarem un enllaç per a restablir la teua contrasenya',
  'send_link': 'Enviar enllaç',
  'email_sent': 'Si l\'email existeix, rebràs un enllaç de recuperació',
  'back_to_login': 'Tornar a l\'inici de sessió',

  // Pantalla principal
  'missions': 'MISSIONS',
  'daily_missions': 'Missions Diàries',
  'missions_completed': 'Missions completades',
  'streak_days': 'Ratxa de dies',
  'mission_snake_play': 'Juga 3 partides de Snake',
  'mission_snake_score': 'Arriba a 50 punts a Snake',
  'mission_snake_score_high': 'Arriba a 100 punts a Snake',
  'mission_watersort_levels': 'Completa 2 nivells de Water Sort',
  'mission_watersort_levels_more': 'Completa 5 nivells de Water Sort',
  'mission_sudoku_complete': 'Completa 1 Sudoku',
  'mission_sudoku_complete_more': 'Completa 3 Sudokus',
  'mission_hangman_win': 'Guanya 2 partides de Penjat',
  'mission_hangman_win_more': 'Guanya 5 partides de Penjat',
  'mission_minesweeper_win': 'Guanya 1 partida de Buscamines',
  'mission_minesweeper_discover': 'Descobreix 20 cel·les a Buscamines',
  'mission_wordsearch_words': 'Troba 10 paraules a Sopa de Lletres',
  'mission_wordsearch_complete': 'Completa 2 Sopes de Lletres',
  'mission_any_play': 'Juga 5 partides de qualsevol joc',
  'mission_any_score': 'Arriba a 100 punts en qualsevol joc',
  'get_pro': 'Adquirix MINIFUN PRO per',
  'pro_price': '€4.99',
  'pro_mode_locked': 'Obtín MINIFUN PRO per accedir a aquesta modalitat',
  'no_hints_left': 'No et queden pistes disponibles',
  'hint_word_starts': 'La paraula comença aquí',
  'hint_safe_cell': 'Aquesta cel·la és segura',
  'hint_next_move': 'Següent moviment suggerit',
  'no_valid_moves': 'No hi ha moviments vàlids disponibles',

  // Noms de jocs
  'game_snake': 'Snake',
  'game_watersort': 'WaterSort',
  'game_word_search': 'Busca de Paraules',
  'game_hangman': 'Penjat',
  'game_minesweeper': 'Buscamines',
  'game_sudoku': 'Sudoku',

  // Verificació de correu electrònic
  'verify_email': 'Verifica el teu correu electrònic',
  'verify_email_desc': 'T\'hem enviat un correu de verificació. Revisa la teua bústia d\'entrada (i la carpeta de spam) per activar el teu compte.',
  'understood': 'Entés',

  // Perfil
  'profile': 'Perfil',
  'edit_profile': 'Editar perfil',
  'change_photo': 'Canviar foto',
  'camera': 'Càmera',
  'gallery': 'Galeria',
  'save_changes': 'Guardar canvis',
  'profile_updated': 'Perfil actualitzat',
  'verify_email_title': 'Verifica el teu email',
  'verify_email_message': "T'hem enviat un correu de verificació al nou email. Revisa la teua safata d'entrada (i la carpeta de spam) per verificar-lo.",
  'delete_photo': 'Eliminar foto',
  'delete_photo_confirm': 'Estàs segur que vols eliminar la teua foto de perfil?',
  'photo_deleted': 'Foto de perfil eliminada',
  'camera_permission_denied': 'Permís de càmera denegat. Activa\'l als ajustos del dispositiu.',

  // Guies
  'guide_of': 'Guia de',
  'objective': 'Objectiu',
  'instructions': 'Instruccions',
  'controls': 'Controls',

  // Guies Snake
  'snake_objective': 'Controla la serp per a menjar pomes i créixer el màxim possible sense xocar amb les parets o amb tu mateix.',
  'snake_inst_1': 'La serp es mou constantment en la direcció seleccionada',
  'snake_inst_2': 'Cada poma que menges farà créixer la teua serp',
  'snake_inst_3': 'La teua puntuació augmenta amb cada poma consumida',
  'snake_inst_4': 'El joc acaba si xoques amb les parets o amb el teu propi cos',
  'snake_inst_5': 'Intenta aconseguir la puntuació més alta possible',
  'control_up': 'Amunt',
  'control_up_desc': 'Llisca cap amunt o pressiona el botó amunt del joystick',
  'control_down': 'Avall',
  'control_down_desc': 'Llisca cap avall o pressiona el botó avall del joystick',
  'control_left': 'Esquerra',
  'control_left_desc': 'Llisca cap a l\'esquerra o pressiona el botó esquerra',
  'control_right': 'Dreta',
  'control_right_desc': 'Llisca cap a la dreta o pressiona el botó dreta',
  'control_joystick': 'Joystick Virtual',
  'control_joystick_desc': 'Usa el D-Pad en la cantonada inferior dreta',
  'control_swipe': 'Lliscar',
  'control_swipe_desc': 'Llisca en qualsevol direcció per moure la serp',

  // Guies Sudoku
  'sudoku_objective': 'Completa el tauler 9x9 amb números de l\'1 al 9, sense repetir en files, columnes o subcuadrícules de 3x3.',
  'sudoku_inst_1': 'Cada fila ha de contindre els números de l\'1 al 9 sense repetir',
  'sudoku_inst_2': 'Cada columna ha de contindre els números de l\'1 al 9 sense repetir',
  'sudoku_inst_3': 'Cada subcuadrícula de 3x3 ha de contindre els números de l\'1 al 9 sense repetir',
  'sudoku_inst_4': 'Els números negres són fixos i no es poden modificar',
  'sudoku_inst_5': 'Els números morats són els que tu col·loques',
  'sudoku_inst_6': 'Usa el mode "Llapis" per a col·locar números que seran validats',
  'sudoku_inst_7': 'Usa el mode "Notes" per a escriure números candidats sense penalització',
  'sudoku_inst_8': 'Si col·loques un número incorrecte en mode llapis, es marcarà en roig',
  'sudoku_inst_9': 'Usa el botó "Pista" si necessites ajuda (no disponible en mode perfecte)',
  'control_select_cell': 'Seleccionar cel·la',
  'control_select_cell_desc': 'Toca una cel·la buida per a seleccionar-la',
  'control_pencil': 'Llapis',
  'control_pencil_desc': 'Col·loca números definitius que seran validats',
  'control_notes': 'Notes',
  'control_notes_desc': 'Escriu notes/candidats sense penalització ni validació',
  'control_place_number': 'Col·locar número',
  'control_place_number_desc': 'Toca un número de l\'1-9 per a col·locar-lo segons el mode actiu',
  'control_erase': 'Esborrar',
  'control_erase_desc': 'Esborra el número i les notes de la cel·la seleccionada',
  'control_hint': 'Pista',
  'control_hint_desc_sudoku': 'Revela el número correcte d\'una cel·la buida',

  // Guies Water Sort
  'watersort_objective': 'Ordena l\'aigua de colors en els tubs fins que cada tub continga un sol color.',
  'watersort_inst_1': 'Toca un tub per a seleccionar-lo',
  'watersort_inst_2': 'Toca un altre tub per a abocar l\'aigua del primer al segon',
  'watersort_inst_3': 'Només pots abocar aigua del mateix color sobre aigua del mateix color',
  'watersort_inst_4': 'També pots abocar en tubs buits',
  'watersort_inst_5': 'Cada tub té capacitat per a 4 segments d\'aigua',
  'watersort_inst_6': 'Completa el nivell quan cada tub tinga un sol color',
  'watersort_inst_7': 'Usa el botó "Desfer" si t\'equivoques',
  'control_select': 'Seleccionar',
  'control_select_desc': 'Toca un tub amb aigua per a seleccionar-lo',
  'control_pour': 'Abocar',
  'control_pour_desc': 'Toca un altre tub per a abocar l\'aigua seleccionada',
  'control_undo': 'Desfer',
  'control_undo_desc': 'Desfà l\'últim moviment realitzat',
  'control_restart': 'Reiniciar',
  'control_restart_desc': 'Reinicia el nivell des del principi',

  // Missatges d'error i notificacions
  'max_flags_reached': '¡Límit màxim de banderes alcançat!',
  'no_safe_cells_for_hint': 'No hi ha caselles segures disponibles per a pista',
  'no_hints_remaining': 'No et queden més pistes disponibles',

  // Guies Sopa de Letras
  'wordsearch_objective': 'Troba totes les paraules ocultes en la quadrícula',
  'wordsearch_inst_1': 'Toca la primera lletra d\'una paraula',
  'wordsearch_inst_2': 'Arrossega el dit fins a l\'última lletra de la paraula',
  'wordsearch_inst_3': 'Les paraules poden estar en horitzontal, vertical o diagonal',
  'wordsearch_inst_4': 'Les paraules poden estar al derecho o al revés',
  'wordsearch_inst_5': 'Les paraules trobades es traçaran de la llista',
  'bonus_word_found': '¡PARAULA EXTRA TROBADA!',
  'bonus_points': '+50 punts',

  // Pausa
  'paused': 'PAUSA',
  'game_paused': 'Joc en Pausa',
  'resume': 'Continuar',

  // Penjat (Ahorcado)
  'hangman_objective': 'Endevina la paraula oculta lletra per lletra abans que es complete el dibuix del penjat.',
  'hangman_inst_1': 'Tens 6 intents per a endevinar la paraula',
  'hangman_inst_2': 'Toca una lletra del teclat per a endevinar',
  'hangman_inst_3': 'Si la lletra està en la paraula, es revelarà',
  'hangman_inst_4': 'Si la lletra no hi és, es dibuixarà una part del penjat',
  'hangman_inst_5': 'Guanyes si endevines totes les lletres abans de completar el dibuix',
  'control_guess_letter': 'Endevinar lletra',
  'control_guess_letter_desc': 'Toca una lletra del teclat per a endevinar-la',
  'theme_animales': 'Animals',
  'theme_paises': 'Països',
  'theme_comida': 'Menjar',
  'theme_ciencia': 'Ciència',
  'theme_deportes': 'Esports',
  'theme_profesiones': 'Professions',
  'theme_geografia': 'Geografia',
  'hangman_speed': 'Velocitat',
  'hangman_survival': 'Supervivència\nPRO',

  // Buscamines
  'minesweeper_objective': 'Descobreix totes les caselles sense mines. Els números indiquen quantes mines hi ha al voltant.',
  'minesweeper_inst_1': 'Toca una casella per a revelar-la',
  'minesweeper_inst_2': 'Els números indiquen mines adjacents',
  'minesweeper_inst_3': 'Mantingues premuda una casella per a posar una bandera',
  'minesweeper_inst_4': 'Si toques una mina, perds',
  'minesweeper_inst_5': 'També pots utilitzar el botó de bandera per a activar-les sense mantenir premut',
  'control_reveal': 'Revelar',
  'control_reveal_desc': 'Toca una casella per a revelar el seu contingut',
  'control_flag': 'Bandera',
  'control_flag_desc': 'Mantingues premut o activa el mode bandera per a marcar mines',
  'control_hint_desc_minesweeper': 'Revela una casella segura aleatòria',

  // Descripcions de dificultat
  'diff_minesweeper_easy': '10x10 - 15 mines',
  'diff_minesweeper_medium': '16x16 - 40 mines',
  'diff_minesweeper_hard': '24x24 - 99 mines',
  'diff_sudoku_easy': 'Moltes cel·les omplertes.',
  'diff_sudoku_medium': 'Repte equilibrat.',
  'diff_sudoku_hard': 'Molt poques pistes.',
  'diff_watersort_easy': 'Nivell d\'entrada.',
  'diff_watersort_medium': 'Més colors i tubs.',
  'diff_watersort_hard': 'Màxima complexitat.',
  'diff_wordsearch_easy': '10x10 - Paraules curtes.',
  'diff_wordsearch_medium': '15x15 - Repte estàndard.',
  'diff_wordsearch_hard': '20x20 - Paraules complexes.',
  'diff_hangman_easy': '8 intents - Paraules comunes.',
  'diff_hangman_medium': '6 intents - Nivell mig.',
  'diff_hangman_hard': '4 intents - Paraules difícils.',

  // PRO Benefits
  'pro_benefits_title': 'Beneficis de MINIFUN PRO',
  'pro_benefits_intro': 'Desbloqueja els modes exclusius:',
  'pro_benefit_snake': 'Supervivència PRO a Snake',
  'pro_benefit_watersort': 'Difícil PRO a Water Sort',
  'pro_benefit_wordsearch': 'Perfecte PRO a Busca de Paraules',
  'pro_benefit_hangman': 'Supervivència PRO a Penjat',
  'pro_benefit_minesweeper_expert': 'Expert a Buscamines',
  'pro_benefit_minesweeper_noflags': 'Sense Banderes a Buscamines',
  'pro_benefit_sudoku': 'Perfecte PRO a Sudoku',
};
